### ISSUE TITLE
Using <> as a proxy tag breaks custom emotes

### ISSUE THREAD

**Issue by miniclip8767** [xSke/PluralKit#370] opened 2021-07-05 01:07 UTC
If someone in your system uses <> as their proxy tags, and you send a message with just custom emotes in, the bot attempts to proxy it for that system member, meaning the emote doesn't appear.

**Comment by spiralw** [comment] 2021-07-05 01:10
Duplicate of #37.

**Closed by spiralw** 2021-07-05 01:10 UTC
Labels: duplicate
