### ISSUE TITLE
Add ability to restrict PK commands to certain role(s) only

### ISSUE THREAD

**Issue by lincolnthedev** [xSke/PluralKit#376] opened 2021-07-30 00:29 UTC
I'm thinking something like:
 - `pk;access`
   - `add <ROLE>`
   - `remove <ROLE>`
   - `list`

Would do this myself, but I don't know C
Thank you in advance

**Comment by spiralw** [comment] 2021-07-30 09:48
Duplicate of #267.

**Closed by spiralw** 2021-07-30 09:48 UTC
Labels: duplicate
